#! /bin/bash -e
# Hacked together by Thorsten von Eicken in 2019
# Modified for use with esp-idf backtrace (no registers) by Steve Glennon in 2022
XTENSA_GDB=~/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gdb

# Validate commandline arguments
if [ -z "$1" ]; then
    echo "usage: $0 <elf file> <backtrace-text>" 1>&2
    exit 1
fi
elf="$1"
if ! [ -f $elf ]; then
    echo "ELF file not found ($elf)" 1>&2
    exit 1
fi

if ! [ -f $XTENSA_GDB ]; then
    echo "xtensa-gdb-esp32-elf-gdb not found ($XTENSA_GDB)" 1>&2
    exit 1
fi

if [ -z "$2" ]; then
    echo "Must provide at least one backtrace pc value, e.g. 0x40015b2f"
    exit 1
else
    bt=$@
fi

declare -a REGS

#echo "BT is ${bt[@]}"

# Parse addresses in backtrace and add them to REGS
n=0
for stk in $bt; do
    # ex: 0x400d38fe
    if [[ $stk =~ 0x40[0-2][0-9a-f]+ ]]; then
        addr=${BASH_REMATCH[0]}
        REGS+=("BT-${n}:${addr}")
    fi
    let "n=$n + 1"
    #[[ $n -gt 10 ]] && break
done

#echo "REGS is ${REGS}"

# Iterate through all addresses and ask GDB to print source info for each one
for reg in "${REGS[@]}"; do
    name=${reg%:*}
    addr=${reg#*:}
    #echo "Checking $name: $addr"
    info=$($XTENSA_GDB --batch $elf -ex "set listsize 1" -ex "l *$addr" -ex q 2>&1 |\
        sed -e 's;/[^ ]*/ESP32/;;' |\
        egrep -v "(No such file or directory)|(^$)") || true
    if [[ -n "$info" ]]; then echo "$name: $info"; fi
done
